apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: nginx-ingress
data:
  # Database configuration
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB_USERS: "users_db"
  POSTGRES_DB_HOTELS: "hotels_db"
  POSTGRES_DB_PAYMENTS: "payments_db"
  POSTGRES_DB_BALANCES: "balances_db"
  POSTGRES_DB_STATISTICS: "reservations_db"
  POSTGRES_DB_RESERVATIONS: "reservations_db"
  
  # RabbitMQ configuration
  RABBIT_MQ_HOST: "rabbitmq-service"
  RABBIT_MQ_PORT: "5672"
  RABBIT_MQ_QUEUE_NAME: "messagequeue"
  RABBIT_MQ_EXCHANGE: "messagequeue-exchange"
  
  # Service hosts and ports
  SESSION_SERVICE_HOST: "session-service"
  SESSION_SERVICE_PORT: "8081"
  HOTEL_SERVICE_HOST: "hotel-service"
  HOTEL_SERVICE_PORT: "8082"
  BOOKING_SERVICE_HOST: "booking-service"
  BOOKING_SERVICE_PORT: "8083"
  PAYMENT_SERVICE_HOST: "payment-service"
  PAYMENT_SERVICE_PORT: "8084"
  LOYALTY_SERVICE_HOST: "loyalty-service"
  LOYALTY_SERVICE_PORT: "8085"
  REPORT_SERVICE_HOST: "report-service"
  REPORT_SERVICE_PORT: "8086"
  GATEWAY_SERVICE_HOST: "gateway-service"
  GATEWAY_SERVICE_PORT: "8087"
